name: CreditCardArchive
options:
  deploymentTarget:
    iOS: "14.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    PRODUCT_BUNDLE_IDENTIFIER: cn.creditcard.archive
    MARKETING_VERSION: "0.3.2"
    CURRENT_PROJECT_VERSION: "8"
    TARGETED_DEVICE_FAMILY: "1,2"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: "YES"
    CODE_SIGN_STYLE: Manual
    CODE_SIGNING_ALLOWED: "NO"
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGN_IDENTITY: ""
    DEVELOPMENT_TEAM: ""
    PROVISIONING_PROFILE_SPECIFIER: ""
targets:
  CreditCardArchive:
    type: application
    platform: iOS
    sources:
      - path: CreditCardArchive
        excludes:
          - Info.plist
          - www/**
    info:
      path: CreditCardArchive/Info.plist
      properties:
        CFBundleDevelopmentRegion: "$(DEVELOPMENT_LANGUAGE)"
        CFBundleDisplayName: 信用卡档案
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: CreditCardArchive
        CFBundlePackageType: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSRequiresIPhoneOS: true
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
